### PR TITLE
Update code.google.com repo to the new location

### PR DESCRIPTION
**Pull request by ernestoalejo**

### CODE REVIEW

**Comment by avelino** [comment]
+1

**Comment by extemporalgenome** [comment]
Please see <github.com/xtgo/slug>, which is the new location for this library and already contains this fix.

**Comment by ernestoalejo** [comment]
@extemporalgenome It will be helpful to add a reference to it in the README or something, as this is the repo that shows up on Google when you search "golang slug"; not the other one.

**Comment by extemporalgenome** [comment]
Ah, I figured I had updated the README. I'll do that soon, thanks.

**Pull request merged**
